version: '3'

services:
  backend:
    build: ./backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    command: "npm run build"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    stdin_open: true

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
